# Aula 01 - Bibliotecas Fundamentais em ML


In [1]:
import pandas as pd


In [2]:
df_excel = pd.read_excel('Chess.xlsx', sheet_name= 'Chess')


In [3]:
df_csv = pd.read_csv('Tomato.csv', sep = ',')


In [4]:
# head = parametro / padrão = 5 linhas 
df_excel.head(10) # primeiras linhas


rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   
5  False  1.504240e+17  1.504240e+17      5           draw   draw   
6   True  1.504230e+17  1.504230e+17     33         resign  white   
7  False  1.503680e+17  1.503680e+17      9         resign  black   
8   True  1.503510e+17  1.503510e+17     66         resign  black   
9   True  1.503440e+17  1.503440e+17    119           mate  white   

  increment_code            white_id  white_rating            black_id  \
0           15+2            bourgris          1500                a-00   
1           5+10                a-00          1322           skinnerua   
2           5+10              ischia          1496                a-00   
3           20+0       daniamurashov          1439        adivanov2009   
4           30+3           nik221107          1523        adivanov2009   
5           10+0           trelynn17          1250       franklin14532   
6           10+0             capa_jr          1520  daniel_likes_chess   
7          15+30  daniel_likes_chess          1413            soultego   
8           15+0           ehabfanri          1439  daniel_likes_chess   
9           10+0  daniel_likes_chess          1381             mirco25   

   black_rating opening_eco  \
0          1191         D10   
1          1261         B00   
2          1500         C20   
3          1454         D02   
4          1469         C41   
5          1002         B27   
6          1423         D00   
7          2108         B00   
8          1392         C50   
9          1209         B01   

                                        opening_name  opening_ply  
0                   Slav Defense: Exchange Variation            5  
1             Nimzowitsch Defense: Kennedy Variation            4  
2              King's Pawn Game: Leonardis Variation            3  
3             Queen's Pawn Game: Zukertort Variation            3  
4                                   Philidor Defense            5  
5               Sicilian Defense: Mongoose Variation            4  
6         Blackmar-Diemer Gambit: Pietrowsky Defense           10  
7  Nimzowitsch Defense: Kennedy Variation |  Link...            5  
8              Italian Game: Schilling-Kostic Gambit            6  
9      Scandinavian Defense: Mieses-Kotroc Variation            4

In [5]:
# tail pega as últimas linhas de um data frame
df_csv.tail()


Date Unit  Minimum  Maximum  Average  Market
2736  2021-05-09   Kg       10       15     12.5  Tomato
2737  2021-05-10   Kg       10       15     12.5  Tomato
2738  2021-05-11   Kg       10       15     12.5  Tomato
2739  2021-05-12   Kg       30       35     32.5  Tomato
2740  2021-05-13   Kg       35       40     37.5  Tomato

In [6]:
# total de linhas e total de colunas (ele conta com o 0, índice começa no zero)
df_csv.shape


(2741, 6)

In [7]:
# para sabermos informacoes da base / object = string
df_excel.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20058 entries, 0 to 20057
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   rated           20058 non-null  bool   
 1   created_at      20058 non-null  float64
 2   last_move_at    20058 non-null  float64
 3   turns           20058 non-null  int64  
 4   victory_status  20058 non-null  object 
 5   winner          20058 non-null  object 
 6   increment_code  20058 non-null  object 
 7   white_id        20058 non-null  object 
 8   white_rating    20058 non-null  int64  
 9   black_id        20058 non-null  object 
 10  black_rating    20058 non-null  int64  
 11  opening_eco     20058 non-null  object 
 12  opening_name    20058 non-null  object 
 13  opening_ply     20058 non-null  int64  
dtypes: bool(1), float64(2), int64(4), object(7)
memory usage: 2.0+ MB


In [8]:
# Estatística básica e descritiva dos dados / std = desvio padrão / a estatísca é feita somente nos dados numéricos
df_csv.describe()


Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

In [9]:
#  transposição da matriz
df_csv.describe().T


count       mean        std   min   25%   50%   75%    max
Minimum  2741.0  35.089748  16.648425   8.0  22.0  30.0  45.0  115.0
Maximum  2741.0  41.281284  17.364135  12.0  30.0  38.0  50.0  120.0
Average  2741.0  38.185516  16.970949  10.0  25.0  35.0  47.5  117.5

In [10]:
# analisar apenas uma coluna (set) --> vide segunda célula
df_excel.head()


rated    created_at  last_move_at  turns victory_status winner  \
0  False  1.504210e+17  1.504210e+17     13      outoftime  white   
1   True  1.504130e+17  1.504130e+17     16         resign  black   
2   True  1.504130e+17  1.504130e+17     61           mate  white   
3   True  1.504110e+17  1.504110e+17     61           mate  white   
4   True  1.504030e+17  1.504030e+17     95           mate  white   

  increment_code       white_id  white_rating      black_id  black_rating  \
0           15+2       bourgris          1500          a-00          1191   
1           5+10           a-00          1322     skinnerua          1261   
2           5+10         ischia          1496          a-00          1500   
3           20+0  daniamurashov          1439  adivanov2009          1454   
4           30+3      nik221107          1523  adivanov2009          1469   

  opening_eco                            opening_name  opening_ply  
0         D10        Slav Defense: Exchange Variation            5  
1         B00  Nimzowitsch Defense: Kennedy Variation            4  
2         C20   King's Pawn Game: Leonardis Variation            3  
3         D02  Queen's Pawn Game: Zukertort Variation            3  
4         C41                        Philidor Defense            5

In [11]:
set(df_excel['victory_status'])


{'draw', 'mate', 'outoftime', 'resign'}

In [12]:
# Criando uma nova coluna / gerando valor 
df_csv.head()


Date Unit  Minimum  Maximum  Average  Market
0  2013-06-16   Kg       26       32     29.0  Tomato
1  2013-06-17   Kg       20       25     22.5  Tomato
2  2013-06-18   Kg       22       26     24.0  Tomato
3  2013-06-19   Kg       24       28     26.0  Tomato
4  2013-06-20   Kg       22       26     24.0  Tomato

In [13]:
df_csv.describe()


Minimum      Maximum      Average
count  2741.000000  2741.000000  2741.000000
mean     35.089748    41.281284    38.185516
std      16.648425    17.364135    16.970949
min       8.000000    12.000000    10.000000
25%      22.000000    30.000000    25.000000
50%      30.000000    38.000000    35.000000
75%      45.000000    50.000000    47.500000
max     115.000000   120.000000   117.500000

In [14]:
# Criando uma função para o df acima
def categorizar_tomate_media(media): # recebe o valor da média
    if media >= 40 and media <= 70:
        return 'tomate medio'
    elif media < 40:
        return 'tomate pequeno'
    else:
        return 'tomatão'


In [15]:
# Aplicando a função e criando a coluna 'Categoria_Tomate'
df_csv['Categoria_Tomate'] = df_csv['Average'].apply(categorizar_tomate_media)


In [16]:
# Visualizando os dados com a aplicação da função
df_csv.head()


Date Unit  Minimum  Maximum  Average  Market Categoria_Tomate
0  2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1  2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2  2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3  2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4  2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno

In [17]:
# Agrupando por categoria 'tomate'
df_csv.groupby(['Categoria_Tomate']).describe()


Minimum                                                      \
                   count       mean       std   min   25%   50%   75%    max   
Categoria_Tomate                                                               
tomate medio       954.0  47.818658  8.203065  30.0  40.0  45.0  55.0   65.0   
tomate pequeno    1638.0  23.978022  7.175572   8.0  18.0  25.0  30.0   38.0   
tomatão            149.0  75.744966  7.324666  65.0  70.0  75.0  80.0  115.0   

                 Maximum             ...              Average             \
                   count       mean  ...   75%    max   count       mean   
Categoria_Tomate                     ...                                   
tomate medio       954.0  55.009434  ...  60.0   75.0   954.0  51.414046   
tomate pequeno    1638.0  29.528694  ...  35.0   44.0  1638.0  26.753358   
tomatão            149.0  82.583893  ...  85.0  120.0   149.0  79.164430   

                                                           
                       std   min   25%   50%   75%    max  
Categoria_Tomate                                           
tomate medio      8.272792  40.0  45.0  50.0  57.5   70.0  
tomate pequeno    7.191735  10.0  21.5  27.5  32.5   39.5  
tomatão           7.367396  70.5  75.0  77.5  82.5  117.5  

[3 rows x 24 columns]

In [18]:
# Filtrando Dados / Localizando Dados
filtro = df_csv['Average'] < 40
df_csv.loc[filtro]


Date Unit  Minimum  Maximum  Average  Market Categoria_Tomate
0     2013-06-16   Kg       26       32     29.0  Tomato   tomate pequeno
1     2013-06-17   Kg       20       25     22.5  Tomato   tomate pequeno
2     2013-06-18   Kg       22       26     24.0  Tomato   tomate pequeno
3     2013-06-19   Kg       24       28     26.0  Tomato   tomate pequeno
4     2013-06-20   Kg       22       26     24.0  Tomato   tomate pequeno
...          ...  ...      ...      ...      ...     ...              ...
2736  2021-05-09   Kg       10       15     12.5  Tomato   tomate pequeno
2737  2021-05-10   Kg       10       15     12.5  Tomato   tomate pequeno
2738  2021-05-11   Kg       10       15     12.5  Tomato   tomate pequeno
2739  2021-05-12   Kg       30       35     32.5  Tomato   tomate pequeno
2740  2021-05-13   Kg       35       40     37.5  Tomato   tomate pequeno

[1638 rows x 7 columns]

Biblioteca Numpy


In [19]:
import numpy as np


In [20]:
# array é uma lista de números
arr_list = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [21]:
print(arr_list)


[1 2 3 4 5 6 7 8]


In [22]:
display(arr_list)


array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
# Criando uma Matriz / tabela preenchidas com zero
arr_zeros = np.zeros((4, 6))
print(arr_zeros)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
# 3 linhas e 4 colunas
arr_ones = np.ones((3,4))  
print(arr_ones)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [27]:
# uma matriz com números aleatórios de 3 a 4 / nunca terá números repetidos
arr_random = np.random.rand(3,4)
print(arr_random)


[[0.17253314 0.3675777  0.52823325 0.65198999]
 [0.86836516 0.31797625 0.74855632 0.96022225]
 [0.94337193 0.22338974 0.46667793 0.73580006]]


In [28]:
# Mostra a dimensão da Matriz
print(arr_random.shape)


(3, 4)


In [29]:
# Reshape: Altera a forma de um array sem modificar seus dados
arr_random_reshape = arr_random.reshape((4,3))
print(arr_random_reshape)


[[0.17253314 0.3675777  0.52823325]
 [0.65198999 0.86836516 0.31797625]
 [0.74855632 0.96022225 0.94337193]
 [0.22338974 0.46667793 0.73580006]]
